# Site settings
title: "Jung Im 'Amy' Choi"
description: "A resume for Jung Im Choi's website."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Jung Im 'Amy' Choi"
resume_title:                   "Data Scientist"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "jchoi3640@yahoo.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "256-653-5035"
resume_contact_address:         "Bowling Green, OH"

resume_header_contact_info:     "742 Evergreen Terrace, Springfield • 555-7334 • lisasimpson@youremailaddress.com"
display_header_contact_info:    "false"

resume_header_intro: "<p>I earned my Ph.D. in Data Science from Bowling Green State University, where my research focused on advancing computer vision and machine learning. Specifically, I explored adversarial robustness, neural network pruning, and deep object detection for autonomous driving. Currently, I am developing cutting-edge methods to enhance the efficiency and adversarial robustness of deep-learning-based visual detectors, addressing critical challenges in resource-constrained and safety-critical environments.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_publications:     true
resume_section_links:           true
#resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_email_url:             "mailto:jchoi3640@yahoo.com"
  #resume_github_url:            "https://github.com/jglovier/resume-template"
  #resume_twitter_url:           "http://twitter.com/jglovier"
  #resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/jung-im-choi-202332317"
  # resume_instagram_url:         "insert your Instagram URL here"
  #resume_website_url:           "http://amy-choi.github.io"
  #resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
